---
version: '3'
services:
  winearth-webui-production:
    build:
      context: ../../
      dockerfile: docker/production/Dockerfile
    image: winearth-webui-production
    restart: always
    ports:
      - "3003:3000"